#!/bin/bash
result=""

for batt in /sys/class/power_supply/BAT*
do
    name=$(echo "$batt" | rev | cut -d/ -f1 | rev)
	if [ -f "$batt/capacity" ]; then
		percentage=$(cat "$batt/capacity")
	elif [ -f "$batt/charge_now" ]; then
		percentage=$(cat "$batt/charge_full" "$batt/charge_now" | tr "\\n" " " | awk '{printf "%.2f", $2/$1*100}')
	elif [ -f "$batt/energy_now" ]; then
		percentage=$(cat "$batt/energy_full" "$batt/energy_now" | tr "\\n" " " | awk '{printf "%.2f", $2/$1*100}')
	fi
    [ $(cat "$batt/subsystem/AC/online") -eq 1 ] && line='+' || line=""
    result="$result $name $line$percentage%"
done

echo $result
