#!/bin/bash

result=""

for therm in /sys/class/thermal/thermal_zone*
do
    temp=$(awk '{ printf "%.1f", $1/1000 }' $therm/temp)
    type=$(cat $therm/type)
    result="$result  $type(${temp}_C)"
done

echo $result
