#!/bin/sh

command -v pulsemixer >/dev/null 2>&1 || (echo "This script need pulsemixer to work properly" && exit 0)

if [ "$1" = "inc" ]; then
	pulsemixer --change-volume +"$2" >/dev/null 2>&1
elif [ "$1" = "dec" ]; then
	pulsemixer --change-volume -"$2" >/dev/null 2>&1
elif [ "$1" = "toggle" ]; then
	pulsemixer --toogle-mute >/dev/null 2>&1
else
	volume=$(echo $(pulsemixer --get-volume) | awk '{printf "L:%d R:%d", $1, $2}')
	mute=$(pulsemixer --get-mute)
	if [ $mute -eq 0 ]; then
		mute=""
	else
		mute="[mute]"
	fi
	echo "$mute$volume"
	exit 0
fi
